### PR TITLE
Adds Kelvin-Helmholtz example

### PR DESCRIPTION
**Pull request by tomchor**
Adds a 3D Kelvin-Helmholtz example. Currently the output is:

https://user-images.githubusercontent.com/13205162/144916292-af21b25c-d38e-4647-9792-d416f08c97c7.mp4

In the future I will run this with both Smag and AMD and hopefully we'll see some different dynamics to exemplify the changes that SGS can make.

### CODE REVIEW

**Comment by glwagner** [comment]
Nice! We sometimes use notation like

```julia
xb, yb, zb = nodes(b)
```

to avoid confusing people with the `C` and `F` / avoid explaining anything about the staggered grid.

Do you want me to convert the example to use `FieldTimeSeries`? It reduces the amount of code by a bit (but isn't necessary of course...)

**Comment by tomchor** [comment]
> Nice! We sometimes use notation like
> 
> ```julia
> xb, yb, zb = nodes(b)
> ```
> 
> to avoid confusing people with the `C` and `F` / avoid explaining anything about the staggered grid.
> 
> Do you want me to convert the example to use `FieldTimeSeries`? It reduces the amount of code by a bit (but isn't necessary of course...)

Sure, if you think it's best and saves some lines of code!

**Comment by tomchor** [comment]
I think I've achieved the result I wanted. This is the output with AMD:

https://user-images.githubusercontent.com/13205162/152423150-eb2264cf-4563-41fc-b0a4-16923e8d0190.mp4

which is a Kelvin-Helmholtz instability like one would expect.

And here's the result with Smagorinsky, which ends up not having any instability at all since the eddy viscosity is super high due to the mean shear:

https://user-images.githubusercontent.com/13205162/152423327-ad939935-c1fd-4985-a274-f83711b892a0.mp4

@glwagner Thoughts? I think this is looking pretty good.

**Comment by glwagner** [comment]
@tomchor sorry I never responded --- those are awesome.

An additional experiment you might try is _no_ closure with WENO5 (eg "implicit" LES).

**Comment by tomchor** [comment]
It would still be good to make those simulations pretties (probably on another PR), but I think these illustrate the main point already.

About implicit LES. Should we talk about that in the tutorial? It isn't _really_ LES, but maybe it's good to talk about names/conventions in the community...

**Comment by glwagner** [comment]
I think a discussion on numerical versus "explicit" dissipation is important. We don't have to call it implicit LES.

I'm not 100% sure what will happen if you run with WENO + no closure, but based on experience it's possible that the code will run stably (and might even "look" pretty good). The result is a vivid and memorable illustration of numerical dissipation.

What's your "definition" of LES?

**Pull request merged**
