### PR TITLE
Free convection script

### PR DESCRIPTION
**Pull request by glwagner**
This PR adds a simple script for simulating free convection. There's a little visualization snippet at the end that produces a movie like this:

https://user-images.githubusercontent.com/15271942/142677685-2c91c0c9-5b28-4c0b-8c71-31f928d260d6.mp4

Needs to be updated in the future to include analysis of the horizontally-averaged fluxes.

### CODE REVIEW

**Comment by tomchor** [comment]
I was gonna plot the resolved and unresolved fluxes in the same animation to start varying the resolution, but I gotta say, I have no idea what's going on in the plotting routine :joy:

**Comment by tomchor** [comment]
Are we committed to only using `jld2`/Julia? I think it's okay if we are (we minimize the number of languages and environments to keep track of), but the downside is that I'll be less able to help you with the plotting routines...

**Comment by glwagner** [comment]
PyPlot is matplotlib (the syntax is identical). Are you familiar with matplotlib? Luckily core routines for other plotting libraries are also virtually identical to matplotlib / matlab with only minor syntax changes. We should stick to simple plotting anyways so any plotting library should be fine.

**Comment by glwagner** [comment]
On JLD2: the main reason to use this is to use minimal plotting and post-processing code by leveraging `FieldTimeSeries`, which we can only use with JLD2 (not for any grave reason, just due to the greater effort required to support the same functionality with NetCDF, which can't serialize julia objects). But I think using something else only incurs a minor cost (the main downside is not introducing people to `FieldTimeSeries`, which hopefully will become a lot more powerful eventually with a bit more love!)

**Comment by glwagner** [comment]
> I was gonna plot the resolved and unresolved fluxes in the same animation to start varying the resolution, but I gotta say, I have no idea what's going on in the plotting routine 😂

I can help. Do you want to plot horizontal averages of those quantities?

**Comment by tomchor** [comment]
> > I was gonna plot the resolved and unresolved fluxes in the same animation to start varying the resolution, but I gotta say, I have no idea what's going on in the plotting routine joy
> 
> I can help. Do you want to plot horizontal averages of those quantities?

My idea was to plot them in the same plot as a side pane. That way we'd be able to vary the resolution and hopefully see the sgs fluxes take over as we decrease the resolution (and vice versa).

**Comment by glwagner** [comment]
Now the script produces

https://user-images.githubusercontent.com/15271942/144864664-2c2dc50c-0e30-4553-ac2a-93e0523d079c.mp4

**Comment by tomchor** [comment]
Thanks!

**Comment by tomchor** [comment]
I've been trying to get this script to work with up to date packages but apparently GLMakie changed some stuff and I've been running into some trouble. Currently this is the error I'm stuck in:

```
ERROR: LoadError: setting limits for scene via plot attribute not supported anymore
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] plot!(scene::Scene, P::Type{Heatmap{Tuple{SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, Matrix{Float64}}}}, attributes::Attributes, input::Tuple{Observable{SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}}, Observable{SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}}, Observable{Matrix{Float64}}}, args::Observable{Tuple{Vector{Float32}, Vector{Float32}, Matrix{Float32}}})
    @ Makie ~/.julia/packages/Makie/14tKQ/src/interfaces.jl:398
  [3] plot!(::Scene, ::Type{Heatmap{ArgType} where ArgType}, ::Attributes, ::SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, ::Vararg{Any, N} where N; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/14tKQ/src/interfaces.jl:319
  [4] plot!(::Scene, ::Type{Heatmap{ArgType} where ArgType}, ::Attributes, ::SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, ::SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, ::Observable{Matrix{Float64}})
    @ Makie ~/.julia/packages/Makie/14tKQ/src/interfaces.jl:287
  [5] plot!(::Axis, ::Type{Heatmap{ArgType} where ArgType}, ::Attributes, ::SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, ::Vararg{Any, N} where N; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie.MakieLayout ~/.julia/packages/Makie/14tKQ/src/makielayout/layoutables/axis.jl:689
  [6] plot!(::Axis, ::Type{Heatmap{ArgType} where ArgType}, ::Attributes, ::SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, ::SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, ::Observable{Matrix{Float64}})
    @ Makie.MakieLayout ~/.julia/packages/Makie/14tKQ/src/makielayout/layoutables/axis.jl:684
  [7] plot!(::Type{Heatmap{ArgType} where ArgType}, ::Axis, ::SubArray{Float64, 1, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, Tuple{UnitRange{Int64}}, true}, ::Vararg{Any, N} where N; kw_attributes::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:limits, :colormap), Tuple{Tuple{Float64, Float64}, Symbol}}})
    @ Makie.MakieLayout ~/.julia/packages/Makie/14tKQ/src/makielayout/layoutables/axis.jl:701
  [8] heatmap!(::Axis, ::Vararg{Any, N} where N; attributes::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:limits, :colormap), Tuple{Tuple{Float64, Float64}, Symbol}}})
    @ MakieCore ~/.julia/packages/MakieCore/A0hGm/src/recipes.jl:37
  [9] top-level scope
    @ ~/repos/tutorial2/free_convection.jl:91
 [10] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [11] top-level scope
    @ REPL[8]:1
in expression starting at /home/tomas/repos/tutorial2/free_convection.jl:91
```

Googling this error doesn't give me useful results...

**Comment by tomchor** [comment]
Currently the animation produces this:

https://user-images.githubusercontent.com/13205162/155751880-d19dcd6b-d4ae-445e-a2d6-fcb048f023ab.mp4

So there's definitely an issue with the plotting of the avg flux (it seems that the fluxes are plotted as tiny lines on the bottom left corner). I can't figure out what it is. The relevant line seems finre to me:


```julia
ax = Axis(fig[1, 5]; xlabel=fluxes_label, ylabel="z (m)")
lines!(ax, wb, z, label="Resolved, ⟨wb⟩")
lines!(ax, qᵇ, z, label="Unresolved, -⟨κₑ ∂z(b)⟩")
```
 @glwagner do you have any idea of what the issue is?

**Pull request merged**
